version: 1.0.0.{build}

platform: x64

branches:
  only:
    - master

skip_tags: true

clone_folder: c:\gopath\src\github.com\markvincze\golang-build-test

environment:
  GOPATH: c:\gopath

install:
  - echo %PATH%
  - echo %GOPATH%
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
    #- rmdir c:\go /s /q
    #- appveyor DownloadFile https://storage.googleapis.com/golang/go1.6.2.windows-amd64.msi
    #- msiexec /i go1.6.2.windows-amd64.msi /q
  - go version
  - go env
  - go get -u github.com/FiloSottile/gvt
    #- mkdir c:\gopath

build_script:
  - ps: .\build.ps1

artifacts:
  - path: hello
    name: binary

deploy:
  release: hello-$(appveyor_build_version)
  description: 'This is a test release'
  provider: GitHub
  auth_token:
    secure: ZkOJAiZBmapKpbiqovaofs+W0foBWaV9Jom4yBYzcRKlAk4Bee+5b7t+5LrQRVn8 # your encrypted token from GitHub
  artifact: hello            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
